name: Delete Releases

on:
  workflow_dispatch:

jobs:
  delete:
    permissions:
      contents: write
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Delete all releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release list --limit 1000 --json tagName \
          | jq -r '.[].tagName' \
          | while read tag; do
              gh release delete "$tag" --yes || true
            done
      - name: Delete all tags from remote
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --tags
          git tag -l | while read tag; do
            git push --delete origin "$tag" || true
          done
